apiVersion: v1
kind: Service
metadata:
  name: guestbook-go-service
spec:
  selector:
    app: guestbook-go
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30001
  type: NodePort
